name: ci-golang-workflow
on: 
  pull_request:
    branches:
    - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    name: Golang {{ matrix.go-version }} test
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go