name: ci-golang-workflow-v2
on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14, 1.15]
    name: Golang ${{ matrix.go-version }} test
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go